# config/cgan_config.yaml

# CGAN model architecture parameters
generator_params:
  latent_dim: 100 # Dimension of the random noise vector
  hidden_dims: [128, 256, 256, 128] # Example layers for Generator
  output_dim: 1 # Always 1 for Log_Id
  activation_function: "GELU"

discriminator_params:
  hidden_dims: [128, 256, 256, 128] # Example layers for Discriminator
  output_dim: 1 # Always 1 for probability
  activation_function: "GELU"

# Training parameters for CGAN
training_params:
  num_epochs: 500
  batch_size: 64
  learning_rate_g: 0.0002 # Learning rate for Generator
  learning_rate_d: 0.0002 # Learning rate for Discriminator
  beta1: 0.5 # Beta1 for Adam optimizer
  criterion: "BCELoss" # Binary Cross-Entropy Loss

# Data generation parameters using the trained CGAN
generation_params:
  num_samples_to_generate: 20000 # Number of synthetic data points to generate
  target_region_for_augmentation: "Cut-off" # The specific region to augment (e.g., Cut-off, Linear, Saturation)
  sample_inputs_from_real_data: True # If True, sample Vgs,Vds,W,L from real data for target region
  # If sample_inputs_from_real_data is False, define ranges:
  # vgs_range: [-0.5, 3.6]
  # vds_range: [0.0, 3.6]
  # w_range: [0.1, 10.0]
  # l_range: [0.1, 10.0]

# Flags for CGAN specific runs
run_flags:
  train_cgan: True # Whether to train the CGAN model
  generate_augmented_data: True # Whether to generate synthetic data after training
  save_generated_data: True # Whether to save the generated data to a CSV
  load_cgan_if_exists: True # If True, load saved GAN models instead of retraining/generating